// Code generated by go-swagger; DO NOT EDIT.

package manage_clusters

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/matyix/oracle-oke-client/models"
)

// NewCreateAuthConfigParams creates a new CreateAuthConfigParams object
// with the default values initialized.
func NewCreateAuthConfigParams() *CreateAuthConfigParams {
	var ()
	return &CreateAuthConfigParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCreateAuthConfigParamsWithTimeout creates a new CreateAuthConfigParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCreateAuthConfigParamsWithTimeout(timeout time.Duration) *CreateAuthConfigParams {
	var ()
	return &CreateAuthConfigParams{

		timeout: timeout,
	}
}

// NewCreateAuthConfigParamsWithContext creates a new CreateAuthConfigParams object
// with the default values initialized, and the ability to set a context for a request
func NewCreateAuthConfigParamsWithContext(ctx context.Context) *CreateAuthConfigParams {
	var ()
	return &CreateAuthConfigParams{

		Context: ctx,
	}
}

// NewCreateAuthConfigParamsWithHTTPClient creates a new CreateAuthConfigParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCreateAuthConfigParamsWithHTTPClient(client *http.Client) *CreateAuthConfigParams {
	var ()
	return &CreateAuthConfigParams{
		HTTPClient: client,
	}
}

/*CreateAuthConfigParams contains all the parameters to send to the API endpoint
for the create auth config operation typically these are written to a http.Request
*/
type CreateAuthConfigParams struct {

	/*Body
	  Body parameters.

	*/
	Body *models.ClustersapiCreateAuthConfigRequest
	/*OwnerID
	  Wercker organization ID.

	Example: 59bbf8affb1beb01009cae7a

	*/
	OwnerID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the create auth config params
func (o *CreateAuthConfigParams) WithTimeout(timeout time.Duration) *CreateAuthConfigParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create auth config params
func (o *CreateAuthConfigParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create auth config params
func (o *CreateAuthConfigParams) WithContext(ctx context.Context) *CreateAuthConfigParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create auth config params
func (o *CreateAuthConfigParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create auth config params
func (o *CreateAuthConfigParams) WithHTTPClient(client *http.Client) *CreateAuthConfigParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create auth config params
func (o *CreateAuthConfigParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the create auth config params
func (o *CreateAuthConfigParams) WithBody(body *models.ClustersapiCreateAuthConfigRequest) *CreateAuthConfigParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the create auth config params
func (o *CreateAuthConfigParams) SetBody(body *models.ClustersapiCreateAuthConfigRequest) {
	o.Body = body
}

// WithOwnerID adds the ownerID to the create auth config params
func (o *CreateAuthConfigParams) WithOwnerID(ownerID string) *CreateAuthConfigParams {
	o.SetOwnerID(ownerID)
	return o
}

// SetOwnerID adds the ownerId to the create auth config params
func (o *CreateAuthConfigParams) SetOwnerID(ownerID string) {
	o.OwnerID = ownerID
}

// WriteToRequest writes these params to a swagger request
func (o *CreateAuthConfigParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param ownerId
	if err := r.SetPathParam("ownerId", o.OwnerID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
