// Code generated by go-swagger; DO NOT EDIT.

package manage_clusters

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/matyix/oracle-oke-client/models"
)

// CreateAuthConfigReader is a Reader for the CreateAuthConfig structure.
type CreateAuthConfigReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateAuthConfigReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewCreateAuthConfigOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewCreateAuthConfigOK creates a CreateAuthConfigOK with default headers values
func NewCreateAuthConfigOK() *CreateAuthConfigOK {
	return &CreateAuthConfigOK{}
}

/*CreateAuthConfigOK handles this case with default header values.

A named credential set (authConfig object) without secrets.
*/
type CreateAuthConfigOK struct {
	Payload *models.ClustersapiAuthConfigInfo
}

func (o *CreateAuthConfigOK) Error() string {
	return fmt.Sprintf("[POST /api/v3/clusters/{ownerId}/authConfigs][%d] createAuthConfigOK  %+v", 200, o.Payload)
}

func (o *CreateAuthConfigOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ClustersapiAuthConfigInfo)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
