// Code generated by go-swagger; DO NOT EDIT.

package manage_clusters

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/matyix/oracle-oke-client/models"
)

// DeleteAuthConfigReader is a Reader for the DeleteAuthConfig structure.
type DeleteAuthConfigReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteAuthConfigReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDeleteAuthConfigOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteAuthConfigOK creates a DeleteAuthConfigOK with default headers values
func NewDeleteAuthConfigOK() *DeleteAuthConfigOK {
	return &DeleteAuthConfigOK{}
}

/*DeleteAuthConfigOK handles this case with default header values.

Empty response body indicating successful deletion.
*/
type DeleteAuthConfigOK struct {
	Payload models.ProtobufEmpty
}

func (o *DeleteAuthConfigOK) Error() string {
	return fmt.Sprintf("[DELETE /api/v3/clusters/{ownerId}/authConfigs/{id}][%d] deleteAuthConfigOK  %+v", 200, o.Payload)
}

func (o *DeleteAuthConfigOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
