// Code generated by go-swagger; DO NOT EDIT.

package manage_clusters

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetWorkItemParams creates a new GetWorkItemParams object
// with the default values initialized.
func NewGetWorkItemParams() *GetWorkItemParams {
	var ()
	return &GetWorkItemParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetWorkItemParamsWithTimeout creates a new GetWorkItemParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetWorkItemParamsWithTimeout(timeout time.Duration) *GetWorkItemParams {
	var ()
	return &GetWorkItemParams{

		timeout: timeout,
	}
}

// NewGetWorkItemParamsWithContext creates a new GetWorkItemParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetWorkItemParamsWithContext(ctx context.Context) *GetWorkItemParams {
	var ()
	return &GetWorkItemParams{

		Context: ctx,
	}
}

// NewGetWorkItemParamsWithHTTPClient creates a new GetWorkItemParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetWorkItemParamsWithHTTPClient(client *http.Client) *GetWorkItemParams {
	var ()
	return &GetWorkItemParams{
		HTTPClient: client,
	}
}

/*GetWorkItemParams contains all the parameters to send to the API endpoint
for the get work item operation typically these are written to a http.Request
*/
type GetWorkItemParams struct {

	/*OwnerID
	  Wercker organization ID.

	Example: 59bbf8affb1beb01009cae7a

	*/
	OwnerID string
	/*WorkItemID
	  Work item ID.

	Example: 993d9a03-bc4c-4709-ad21-68c816267464

	*/
	WorkItemID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get work item params
func (o *GetWorkItemParams) WithTimeout(timeout time.Duration) *GetWorkItemParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get work item params
func (o *GetWorkItemParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get work item params
func (o *GetWorkItemParams) WithContext(ctx context.Context) *GetWorkItemParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get work item params
func (o *GetWorkItemParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get work item params
func (o *GetWorkItemParams) WithHTTPClient(client *http.Client) *GetWorkItemParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get work item params
func (o *GetWorkItemParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithOwnerID adds the ownerID to the get work item params
func (o *GetWorkItemParams) WithOwnerID(ownerID string) *GetWorkItemParams {
	o.SetOwnerID(ownerID)
	return o
}

// SetOwnerID adds the ownerId to the get work item params
func (o *GetWorkItemParams) SetOwnerID(ownerID string) {
	o.OwnerID = ownerID
}

// WithWorkItemID adds the workItemID to the get work item params
func (o *GetWorkItemParams) WithWorkItemID(workItemID string) *GetWorkItemParams {
	o.SetWorkItemID(workItemID)
	return o
}

// SetWorkItemID adds the workItemId to the get work item params
func (o *GetWorkItemParams) SetWorkItemID(workItemID string) {
	o.WorkItemID = workItemID
}

// WriteToRequest writes these params to a swagger request
func (o *GetWorkItemParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param ownerId
	if err := r.SetPathParam("ownerId", o.OwnerID); err != nil {
		return err
	}

	// path param workItemId
	if err := r.SetPathParam("workItemId", o.WorkItemID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
