// Code generated by go-swagger; DO NOT EDIT.

package manage_clusters

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/matyix/oracle-oke-client/models"
)

// GetNodeImagesReader is a Reader for the GetNodeImages structure.
type GetNodeImagesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetNodeImagesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetNodeImagesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetNodeImagesOK creates a GetNodeImagesOK with default headers values
func NewGetNodeImagesOK() *GetNodeImagesOK {
	return &GetNodeImagesOK{}
}

/*GetNodeImagesOK handles this case with default header values.

List of supported OS images.
*/
type GetNodeImagesOK struct {
	Payload *models.ClustersapiGetNodeImagesResponse
}

func (o *GetNodeImagesOK) Error() string {
	return fmt.Sprintf("[POST /api/v3/clusters/{ownerId}/node/images][%d] getNodeImagesOK  %+v", 200, o.Payload)
}

func (o *GetNodeImagesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ClustersapiGetNodeImagesResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
