// Code generated by go-swagger; DO NOT EDIT.

package manage_clusters

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/matyix/oracle-oke-client/models"
)

// GetAuthConfigReader is a Reader for the GetAuthConfig structure.
type GetAuthConfigReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAuthConfigReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetAuthConfigOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetAuthConfigOK creates a GetAuthConfigOK with default headers values
func NewGetAuthConfigOK() *GetAuthConfigOK {
	return &GetAuthConfigOK{}
}

/*GetAuthConfigOK handles this case with default header values.

Named credential set (authConfig object) details.
*/
type GetAuthConfigOK struct {
	Payload *models.ClustersapiAuthConfigInfo
}

func (o *GetAuthConfigOK) Error() string {
	return fmt.Sprintf("[GET /api/v3/clusters/{ownerId}/authConfigs/{id}][%d] getAuthConfigOK  %+v", 200, o.Payload)
}

func (o *GetAuthConfigOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ClustersapiAuthConfigInfo)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
