// Code generated by go-swagger; DO NOT EDIT.

package manage_clusters

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/matyix/oracle-oke-client/models"
)

// NewGetRegionParams creates a new GetRegionParams object
// with the default values initialized.
func NewGetRegionParams() *GetRegionParams {
	var ()
	return &GetRegionParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetRegionParamsWithTimeout creates a new GetRegionParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetRegionParamsWithTimeout(timeout time.Duration) *GetRegionParams {
	var ()
	return &GetRegionParams{

		timeout: timeout,
	}
}

// NewGetRegionParamsWithContext creates a new GetRegionParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetRegionParamsWithContext(ctx context.Context) *GetRegionParams {
	var ()
	return &GetRegionParams{

		Context: ctx,
	}
}

// NewGetRegionParamsWithHTTPClient creates a new GetRegionParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetRegionParamsWithHTTPClient(client *http.Client) *GetRegionParams {
	var ()
	return &GetRegionParams{
		HTTPClient: client,
	}
}

/*GetRegionParams contains all the parameters to send to the API endpoint
for the get region operation typically these are written to a http.Request
*/
type GetRegionParams struct {

	/*Body
	  Body parameters.

	*/
	Body *models.ClustersapiGetRegionRequest
	/*OwnerID
	  Wercker organization ID.

	Example: 59bbf8affb1beb01009cae7a

	*/
	OwnerID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get region params
func (o *GetRegionParams) WithTimeout(timeout time.Duration) *GetRegionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get region params
func (o *GetRegionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get region params
func (o *GetRegionParams) WithContext(ctx context.Context) *GetRegionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get region params
func (o *GetRegionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get region params
func (o *GetRegionParams) WithHTTPClient(client *http.Client) *GetRegionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get region params
func (o *GetRegionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the get region params
func (o *GetRegionParams) WithBody(body *models.ClustersapiGetRegionRequest) *GetRegionParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the get region params
func (o *GetRegionParams) SetBody(body *models.ClustersapiGetRegionRequest) {
	o.Body = body
}

// WithOwnerID adds the ownerID to the get region params
func (o *GetRegionParams) WithOwnerID(ownerID string) *GetRegionParams {
	o.SetOwnerID(ownerID)
	return o
}

// SetOwnerID adds the ownerId to the get region params
func (o *GetRegionParams) SetOwnerID(ownerID string) {
	o.OwnerID = ownerID
}

// WriteToRequest writes these params to a swagger request
func (o *GetRegionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param ownerId
	if err := r.SetPathParam("ownerId", o.OwnerID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
