// Code generated by go-swagger; DO NOT EDIT.

package manage_clusters

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/matyix/oracle-oke-client/models"
)

// GetWorkItemReader is a Reader for the GetWorkItem structure.
type GetWorkItemReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetWorkItemReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetWorkItemOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetWorkItemOK creates a GetWorkItemOK with default headers values
func NewGetWorkItemOK() *GetWorkItemOK {
	return &GetWorkItemOK{}
}

/*GetWorkItemOK handles this case with default header values.

Details of operation specified by workItemId.
*/
type GetWorkItemOK struct {
	Payload *models.ClustersapiGetWorkItemResponse
}

func (o *GetWorkItemOK) Error() string {
	return fmt.Sprintf("[GET /api/v3/clusters/{ownerId}/workItems/{workItemId}][%d] getWorkItemOK  %+v", 200, o.Payload)
}

func (o *GetWorkItemOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ClustersapiGetWorkItemResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
