// Code generated by go-swagger; DO NOT EDIT.

package manage_clusters

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/matyix/oracle-oke-client/models"
)

// GetBmcAdsReader is a Reader for the GetBmcAds structure.
type GetBmcAdsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetBmcAdsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetBmcAdsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetBmcAdsOK creates a GetBmcAdsOK with default headers values
func NewGetBmcAdsOK() *GetBmcAdsOK {
	return &GetBmcAdsOK{}
}

/*GetBmcAdsOK handles this case with default header values.

List of Availability Domains.
*/
type GetBmcAdsOK struct {
	Payload *models.ClustersapiGetBmcAdsResponse
}

func (o *GetBmcAdsOK) Error() string {
	return fmt.Sprintf("[POST /api/v3/clusters/{ownerId}/bmc/ads][%d] getBmcAdsOK  %+v", 200, o.Payload)
}

func (o *GetBmcAdsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ClustersapiGetBmcAdsResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
