// Code generated by go-swagger; DO NOT EDIT.

package manage_clusters

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/matyix/oracle-oke-client/models"
)

// GetK8SVersionsReader is a Reader for the GetK8SVersions structure.
type GetK8SVersionsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetK8SVersionsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetK8SVersionsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetK8SVersionsOK creates a GetK8SVersionsOK with default headers values
func NewGetK8SVersionsOK() *GetK8SVersionsOK {
	return &GetK8SVersionsOK{}
}

/*GetK8SVersionsOK handles this case with default header values.

List of supported Kubernetes versions.
*/
type GetK8SVersionsOK struct {
	Payload *models.ClustersapiGetK8SVersionsResponse
}

func (o *GetK8SVersionsOK) Error() string {
	return fmt.Sprintf("[POST /api/v3/clusters/{ownerId}/k8sVersions][%d] getK8SVersionsOK  %+v", 200, o.Payload)
}

func (o *GetK8SVersionsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ClustersapiGetK8SVersionsResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
