// Code generated by go-swagger; DO NOT EDIT.

package manage_clusters

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/matyix/oracle-oke-client/models"
)

// NewGetBmcAdsParams creates a new GetBmcAdsParams object
// with the default values initialized.
func NewGetBmcAdsParams() *GetBmcAdsParams {
	var ()
	return &GetBmcAdsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetBmcAdsParamsWithTimeout creates a new GetBmcAdsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetBmcAdsParamsWithTimeout(timeout time.Duration) *GetBmcAdsParams {
	var ()
	return &GetBmcAdsParams{

		timeout: timeout,
	}
}

// NewGetBmcAdsParamsWithContext creates a new GetBmcAdsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetBmcAdsParamsWithContext(ctx context.Context) *GetBmcAdsParams {
	var ()
	return &GetBmcAdsParams{

		Context: ctx,
	}
}

// NewGetBmcAdsParamsWithHTTPClient creates a new GetBmcAdsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetBmcAdsParamsWithHTTPClient(client *http.Client) *GetBmcAdsParams {
	var ()
	return &GetBmcAdsParams{
		HTTPClient: client,
	}
}

/*GetBmcAdsParams contains all the parameters to send to the API endpoint
for the get bmc ads operation typically these are written to a http.Request
*/
type GetBmcAdsParams struct {

	/*Body
	  Body parameters.

	*/
	Body *models.ClustersapiGetBmcAdsRequest
	/*OwnerID
	  Wercker organization ID.

	Example: 59bbf8affb1beb01009cae7a

	*/
	OwnerID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get bmc ads params
func (o *GetBmcAdsParams) WithTimeout(timeout time.Duration) *GetBmcAdsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get bmc ads params
func (o *GetBmcAdsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get bmc ads params
func (o *GetBmcAdsParams) WithContext(ctx context.Context) *GetBmcAdsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get bmc ads params
func (o *GetBmcAdsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get bmc ads params
func (o *GetBmcAdsParams) WithHTTPClient(client *http.Client) *GetBmcAdsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get bmc ads params
func (o *GetBmcAdsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the get bmc ads params
func (o *GetBmcAdsParams) WithBody(body *models.ClustersapiGetBmcAdsRequest) *GetBmcAdsParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the get bmc ads params
func (o *GetBmcAdsParams) SetBody(body *models.ClustersapiGetBmcAdsRequest) {
	o.Body = body
}

// WithOwnerID adds the ownerID to the get bmc ads params
func (o *GetBmcAdsParams) WithOwnerID(ownerID string) *GetBmcAdsParams {
	o.SetOwnerID(ownerID)
	return o
}

// SetOwnerID adds the ownerId to the get bmc ads params
func (o *GetBmcAdsParams) SetOwnerID(ownerID string) {
	o.OwnerID = ownerID
}

// WriteToRequest writes these params to a swagger request
func (o *GetBmcAdsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param ownerId
	if err := r.SetPathParam("ownerId", o.OwnerID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
