// Code generated by go-swagger; DO NOT EDIT.

package manage_clusters

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewListAuthConfigsParams creates a new ListAuthConfigsParams object
// with the default values initialized.
func NewListAuthConfigsParams() *ListAuthConfigsParams {
	var ()
	return &ListAuthConfigsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewListAuthConfigsParamsWithTimeout creates a new ListAuthConfigsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewListAuthConfigsParamsWithTimeout(timeout time.Duration) *ListAuthConfigsParams {
	var ()
	return &ListAuthConfigsParams{

		timeout: timeout,
	}
}

// NewListAuthConfigsParamsWithContext creates a new ListAuthConfigsParams object
// with the default values initialized, and the ability to set a context for a request
func NewListAuthConfigsParamsWithContext(ctx context.Context) *ListAuthConfigsParams {
	var ()
	return &ListAuthConfigsParams{

		Context: ctx,
	}
}

// NewListAuthConfigsParamsWithHTTPClient creates a new ListAuthConfigsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewListAuthConfigsParamsWithHTTPClient(client *http.Client) *ListAuthConfigsParams {
	var ()
	return &ListAuthConfigsParams{
		HTTPClient: client,
	}
}

/*ListAuthConfigsParams contains all the parameters to send to the API endpoint
for the list auth configs operation typically these are written to a http.Request
*/
type ListAuthConfigsParams struct {

	/*OwnerID
	  Wercker organization ID.

	Example: 59bbf8affb1beb01009cae7a

	*/
	OwnerID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the list auth configs params
func (o *ListAuthConfigsParams) WithTimeout(timeout time.Duration) *ListAuthConfigsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list auth configs params
func (o *ListAuthConfigsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list auth configs params
func (o *ListAuthConfigsParams) WithContext(ctx context.Context) *ListAuthConfigsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list auth configs params
func (o *ListAuthConfigsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list auth configs params
func (o *ListAuthConfigsParams) WithHTTPClient(client *http.Client) *ListAuthConfigsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list auth configs params
func (o *ListAuthConfigsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithOwnerID adds the ownerID to the list auth configs params
func (o *ListAuthConfigsParams) WithOwnerID(ownerID string) *ListAuthConfigsParams {
	o.SetOwnerID(ownerID)
	return o
}

// SetOwnerID adds the ownerId to the list auth configs params
func (o *ListAuthConfigsParams) SetOwnerID(ownerID string) {
	o.OwnerID = ownerID
}

// WriteToRequest writes these params to a swagger request
func (o *ListAuthConfigsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param ownerId
	if err := r.SetPathParam("ownerId", o.OwnerID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
