// Code generated by go-swagger; DO NOT EDIT.

package manage_clusters

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/matyix/oracle-oke-client/models"
)

// ListAuthConfigsReader is a Reader for the ListAuthConfigs structure.
type ListAuthConfigsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListAuthConfigsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewListAuthConfigsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewListAuthConfigsOK creates a ListAuthConfigsOK with default headers values
func NewListAuthConfigsOK() *ListAuthConfigsOK {
	return &ListAuthConfigsOK{}
}

/*ListAuthConfigsOK handles this case with default header values.

List of named credential sets (authConfig objects).
*/
type ListAuthConfigsOK struct {
	Payload *models.ClustersapiListAuthConfigsResponse
}

func (o *ListAuthConfigsOK) Error() string {
	return fmt.Sprintf("[GET /api/v3/clusters/{ownerId}/authConfigs][%d] listAuthConfigsOK  %+v", 200, o.Payload)
}

func (o *ListAuthConfigsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ClustersapiListAuthConfigsResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
