// Code generated by go-swagger; DO NOT EDIT.

package manage_clusters

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/matyix/oracle-oke-client/models"
)

// UpdatePoolsReader is a Reader for the UpdatePools structure.
type UpdatePoolsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdatePoolsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewUpdatePoolsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewUpdatePoolsOK creates a UpdatePoolsOK with default headers values
func NewUpdatePoolsOK() *UpdatePoolsOK {
	return &UpdatePoolsOK{}
}

/*UpdatePoolsOK handles this case with default header values.

Cluster pools.
*/
type UpdatePoolsOK struct {
	Payload *models.ClustersapiUpdatePoolsResponse
}

func (o *UpdatePoolsOK) Error() string {
	return fmt.Sprintf("[PUT /api/v3/clusters/{ownerId}/{clusterId}/pools][%d] updatePoolsOK  %+v", 200, o.Payload)
}

func (o *UpdatePoolsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ClustersapiUpdatePoolsResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
