// Code generated by go-swagger; DO NOT EDIT.

package manage_clusters

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/matyix/oracle-oke-client/models"
)

// NewUpgradeK8SMasterParams creates a new UpgradeK8SMasterParams object
// with the default values initialized.
func NewUpgradeK8SMasterParams() *UpgradeK8SMasterParams {
	var ()
	return &UpgradeK8SMasterParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUpgradeK8SMasterParamsWithTimeout creates a new UpgradeK8SMasterParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUpgradeK8SMasterParamsWithTimeout(timeout time.Duration) *UpgradeK8SMasterParams {
	var ()
	return &UpgradeK8SMasterParams{

		timeout: timeout,
	}
}

// NewUpgradeK8SMasterParamsWithContext creates a new UpgradeK8SMasterParams object
// with the default values initialized, and the ability to set a context for a request
func NewUpgradeK8SMasterParamsWithContext(ctx context.Context) *UpgradeK8SMasterParams {
	var ()
	return &UpgradeK8SMasterParams{

		Context: ctx,
	}
}

// NewUpgradeK8SMasterParamsWithHTTPClient creates a new UpgradeK8SMasterParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUpgradeK8SMasterParamsWithHTTPClient(client *http.Client) *UpgradeK8SMasterParams {
	var ()
	return &UpgradeK8SMasterParams{
		HTTPClient: client,
	}
}

/*UpgradeK8SMasterParams contains all the parameters to send to the API endpoint
for the upgrade k8 s master operation typically these are written to a http.Request
*/
type UpgradeK8SMasterParams struct {

	/*Body
	  Body parameters.

	*/
	Body *models.ClustersapiUpgradeK8SMasterRequest
	/*ClusterID
	  Cluster ID.

	Example: a5a19a4776

	*/
	ClusterID string
	/*OwnerID
	  Wercker organization ID.

	Example: 59bbf8affb1beb01009cae7a

	*/
	OwnerID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the upgrade k8 s master params
func (o *UpgradeK8SMasterParams) WithTimeout(timeout time.Duration) *UpgradeK8SMasterParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the upgrade k8 s master params
func (o *UpgradeK8SMasterParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the upgrade k8 s master params
func (o *UpgradeK8SMasterParams) WithContext(ctx context.Context) *UpgradeK8SMasterParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the upgrade k8 s master params
func (o *UpgradeK8SMasterParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the upgrade k8 s master params
func (o *UpgradeK8SMasterParams) WithHTTPClient(client *http.Client) *UpgradeK8SMasterParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the upgrade k8 s master params
func (o *UpgradeK8SMasterParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the upgrade k8 s master params
func (o *UpgradeK8SMasterParams) WithBody(body *models.ClustersapiUpgradeK8SMasterRequest) *UpgradeK8SMasterParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the upgrade k8 s master params
func (o *UpgradeK8SMasterParams) SetBody(body *models.ClustersapiUpgradeK8SMasterRequest) {
	o.Body = body
}

// WithClusterID adds the clusterID to the upgrade k8 s master params
func (o *UpgradeK8SMasterParams) WithClusterID(clusterID string) *UpgradeK8SMasterParams {
	o.SetClusterID(clusterID)
	return o
}

// SetClusterID adds the clusterId to the upgrade k8 s master params
func (o *UpgradeK8SMasterParams) SetClusterID(clusterID string) {
	o.ClusterID = clusterID
}

// WithOwnerID adds the ownerID to the upgrade k8 s master params
func (o *UpgradeK8SMasterParams) WithOwnerID(ownerID string) *UpgradeK8SMasterParams {
	o.SetOwnerID(ownerID)
	return o
}

// SetOwnerID adds the ownerId to the upgrade k8 s master params
func (o *UpgradeK8SMasterParams) SetOwnerID(ownerID string) {
	o.OwnerID = ownerID
}

// WriteToRequest writes these params to a swagger request
func (o *UpgradeK8SMasterParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param clusterId
	if err := r.SetPathParam("clusterId", o.ClusterID); err != nil {
		return err
	}

	// path param ownerId
	if err := r.SetPathParam("ownerId", o.OwnerID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
