// Code generated by go-swagger; DO NOT EDIT.

package manage_clusters

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/matyix/oracle-oke-client/models"
)

// UpgradeK8SMasterReader is a Reader for the UpgradeK8SMaster structure.
type UpgradeK8SMasterReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpgradeK8SMasterReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewUpgradeK8SMasterOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewUpgradeK8SMasterOK creates a UpgradeK8SMasterOK with default headers values
func NewUpgradeK8SMasterOK() *UpgradeK8SMasterOK {
	return &UpgradeK8SMasterOK{}
}

/*UpgradeK8SMasterOK handles this case with default header values.

Upgrade details.
*/
type UpgradeK8SMasterOK struct {
	Payload *models.ClustersapiUpgradeK8SMasterResponse
}

func (o *UpgradeK8SMasterOK) Error() string {
	return fmt.Sprintf("[POST /api/v3/clusters/{ownerId}/{clusterId}/upgradeK8SMaster][%d] upgradeK8SMasterOK  %+v", 200, o.Payload)
}

func (o *UpgradeK8SMasterOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ClustersapiUpgradeK8SMasterResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
