// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ClustersapiWorkerDetails Schema description.
// swagger:model clustersapiWorkerDetails
type ClustersapiWorkerDetails struct {

	// Parameter description.
	AvailabilityDomain string `json:"availabilityDomain,omitempty"`

	// Parameter description.
	BmcLifecycleState string `json:"bmcLifecycleState,omitempty"`

	// Parameter description.
	CompartmentID string `json:"compartmentId,omitempty"`

	// Parameter description.
	CompartmentName string `json:"compartmentName,omitempty"`

	// Parameter description.
	Error *ClustersapiWorkerErrors `json:"error,omitempty"`

	// Parameter description.
	ID string `json:"id,omitempty"`

	// Parameter description.
	ImageID string `json:"imageId,omitempty"`

	// Parameter description.
	ImageName string `json:"imageName,omitempty"`

	// Kubernetes version.
	K8Version string `json:"k8Version,omitempty"`

	// Parameter description.
	Name string `json:"name,omitempty"`

	// Parameter description.
	Pool string `json:"pool,omitempty"`

	// Parameter description.
	PublicIP string `json:"publicIp,omitempty"`

	// Parameter description.
	Region string `json:"region,omitempty"`

	// Parameter description.
	Shape string `json:"shape,omitempty"`

	// Parameter description.
	Slot int32 `json:"slot,omitempty"`

	// Parameter description.
	SubnetID string `json:"subnetId,omitempty"`

	// Parameter description.
	WorkerStatus string `json:"workerStatus,omitempty"`
}

// Validate validates this clustersapi worker details
func (m *ClustersapiWorkerDetails) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateError(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ClustersapiWorkerDetails) validateError(formats strfmt.Registry) error {

	if swag.IsZero(m.Error) { // not required
		return nil
	}

	if m.Error != nil {

		if err := m.Error.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("error")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ClustersapiWorkerDetails) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ClustersapiWorkerDetails) UnmarshalBinary(b []byte) error {
	var res ClustersapiWorkerDetails
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
