// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ClustersapiUpdatePoolsResponse The response to an update pools request.
// swagger:model clustersapiUpdatePoolsResponse
type ClustersapiUpdatePoolsResponse struct {

	// Work item ID.
	WorkItemID string `json:"workItemId,omitempty"`
}

// Validate validates this clustersapi update pools response
func (m *ClustersapiUpdatePoolsResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *ClustersapiUpdatePoolsResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ClustersapiUpdatePoolsResponse) UnmarshalBinary(b []byte) error {
	var res ClustersapiUpdatePoolsResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
