// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ClustersapiGetK8SVersionsRequest This object contains the details required to get the available Kubernetes versions.
// swagger:model clustersapiGetK8SVersionsRequest
type ClustersapiGetK8SVersionsRequest struct {

	// Credential set ID.
	CloudAuthID string `json:"cloudAuthId,omitempty"`

	// Wercker organization ID.
	OwnerID string `json:"ownerId,omitempty"`
}

// Validate validates this clustersapi get k8 s versions request
func (m *ClustersapiGetK8SVersionsRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *ClustersapiGetK8SVersionsRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ClustersapiGetK8SVersionsRequest) UnmarshalBinary(b []byte) error {
	var res ClustersapiGetK8SVersionsRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
