// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ClustersapiClusterDetails Cluster details.
// swagger:model clustersapiClusterDetails
type ClustersapiClusterDetails struct {

	// k8
	K8 *ClustersapiCluster `json:"k8,omitempty"`

	// workers
	Workers ClustersapiClusterDetailsWorkers `json:"workers"`
}

// Validate validates this clustersapi cluster details
func (m *ClustersapiClusterDetails) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateK8(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ClustersapiClusterDetails) validateK8(formats strfmt.Registry) error {

	if swag.IsZero(m.K8) { // not required
		return nil
	}

	if m.K8 != nil {

		if err := m.K8.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("k8")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ClustersapiClusterDetails) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ClustersapiClusterDetails) UnmarshalBinary(b []byte) error {
	var res ClustersapiClusterDetails
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
