// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ClustersapiGetNodeShapesRequest Schema description.
// swagger:model clustersapiGetNodeShapesRequest
type ClustersapiGetNodeShapesRequest struct {

	// Credential set ID.
	CloudAuthID string `json:"cloudAuthId,omitempty"`

	// Wercker organization ID.
	OwnerID string `json:"ownerId,omitempty"`
}

// Validate validates this clustersapi get node shapes request
func (m *ClustersapiGetNodeShapesRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *ClustersapiGetNodeShapesRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ClustersapiGetNodeShapesRequest) UnmarshalBinary(b []byte) error {
	var res ClustersapiGetNodeShapesRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
