// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ClustersapiEndpoints Cluster endpoint details.
// swagger:model clustersapiEndpoints
type ClustersapiEndpoints struct {

	// The cluster etcd endpoint.
	Etcd string `json:"etcd,omitempty"`

	// The Kubernetes master endpoint.
	K8 string `json:"k8,omitempty"`

	// The tenant agent endpoint.
	TenantAgent string `json:"tenantAgent,omitempty"`
}

// Validate validates this clustersapi endpoints
func (m *ClustersapiEndpoints) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *ClustersapiEndpoints) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ClustersapiEndpoints) UnmarshalBinary(b []byte) error {
	var res ClustersapiEndpoints
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
