// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ClustersapiRollup Schema description.
// swagger:model clustersapiRollup
type ClustersapiRollup struct {

	// Number of nodes being provisioned.
	Provisioning int32 `json:"provisioning,omitempty"`

	// Number of nodes that are running.
	Running int32 `json:"running,omitempty"`
}

// Validate validates this clustersapi rollup
func (m *ClustersapiRollup) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *ClustersapiRollup) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ClustersapiRollup) UnmarshalBinary(b []byte) error {
	var res ClustersapiRollup
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
