// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ClustersapiUpgradeK8SMasterResponse Upgrade Kubernetes master response.
// swagger:model clustersapiUpgradeK8SMasterResponse
type ClustersapiUpgradeK8SMasterResponse struct {

	// Cluster ID.
	ClusterID string `json:"clusterId,omitempty"`

	// Work item ID.
	WorkItemID string `json:"workItemId,omitempty"`
}

// Validate validates this clustersapi upgrade k8 s master response
func (m *ClustersapiUpgradeK8SMasterResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *ClustersapiUpgradeK8SMasterResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ClustersapiUpgradeK8SMasterResponse) UnmarshalBinary(b []byte) error {
	var res ClustersapiUpgradeK8SMasterResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
