// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ClustersapiVersion This object contains API details.
// swagger:model clustersapiVersion
type ClustersapiVersion struct {

	// Build branch.
	BuildBranch string `json:"buildBranch,omitempty"`

	// API build date.
	BuildDate string `json:"buildDate,omitempty"`

	// The ID of the build host.
	BuildHost string `json:"buildHost,omitempty"`

	// The git commit ID
	GitCommit string `json:"gitCommit,omitempty"`

	// Release branch.
	Release string `json:"release,omitempty"`

	// API version.
	Version string `json:"version,omitempty"`
}

// Validate validates this clustersapi version
func (m *ClustersapiVersion) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *ClustersapiVersion) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ClustersapiVersion) UnmarshalBinary(b []byte) error {
	var res ClustersapiVersion
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
