// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ClustersapiGetBmcAdsResponse clustersapi get bmc ads response
// swagger:model clustersapiGetBmcAdsResponse
type ClustersapiGetBmcAdsResponse struct {

	// ads
	Ads ClustersapiGetBmcAdsResponseAds `json:"ads"`
}

// Validate validates this clustersapi get bmc ads response
func (m *ClustersapiGetBmcAdsResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *ClustersapiGetBmcAdsResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ClustersapiGetBmcAdsResponse) UnmarshalBinary(b []byte) error {
	var res ClustersapiGetBmcAdsResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
