// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ClustersapiStateDetails Schema description.
// swagger:model clustersapiStateDetails
type ClustersapiStateDetails struct {

	// nodes rollup
	NodesRollup *ClustersapiRollup `json:"nodesRollup,omitempty"`
}

// Validate validates this clustersapi state details
func (m *ClustersapiStateDetails) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateNodesRollup(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ClustersapiStateDetails) validateNodesRollup(formats strfmt.Registry) error {

	if swag.IsZero(m.NodesRollup) { // not required
		return nil
	}

	if m.NodesRollup != nil {

		if err := m.NodesRollup.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("nodesRollup")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ClustersapiStateDetails) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ClustersapiStateDetails) UnmarshalBinary(b []byte) error {
	var res ClustersapiStateDetails
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
