// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ClustersapiActivity clustersapi activity
// swagger:model clustersapiActivity
type ClustersapiActivity struct {

	// Parameter description.
	CreatedAt string `json:"createdAt,omitempty"`

	// Parameter description.
	Message string `json:"message,omitempty"`
}

// Validate validates this clustersapi activity
func (m *ClustersapiActivity) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *ClustersapiActivity) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ClustersapiActivity) UnmarshalBinary(b []byte) error {
	var res ClustersapiActivity
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
