// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ClustersapiGetBmcAdsRequest clustersapi get bmc ads request
// swagger:model clustersapiGetBmcAdsRequest
type ClustersapiGetBmcAdsRequest struct {

	// Credential set ID.
	CloudAuthID string `json:"cloudAuthId,omitempty"`

	// Compartment ID.
	CompartmentOcid string `json:"compartmentOcid,omitempty"`

	// Wercker organization ID.
	OwnerID string `json:"ownerId,omitempty"`
}

// Validate validates this clustersapi get bmc ads request
func (m *ClustersapiGetBmcAdsRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *ClustersapiGetBmcAdsRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ClustersapiGetBmcAdsRequest) UnmarshalBinary(b []byte) error {
	var res ClustersapiGetBmcAdsRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
