// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ClustersapiAuthConfigBmc This object contains information about the cloud infrastructure.
// swagger:model clustersapiAuthConfigBmc
type ClustersapiAuthConfigBmc struct {

	// The fingerprint of the public key.
	Fingerprint string `json:"fingerprint,omitempty"`

	// The RSA private key used to access the OCI API. Passphrase-protected private keys are not allowed.
	PrivateKey string `json:"privateKey,omitempty"`

	// The region where the cluster resides.
	Region string `json:"region,omitempty"`

	// The OCID of the tenancy where the cluster resides.
	Tenancy string `json:"tenancy,omitempty"`

	// The OCID of the user with which to log into the tenancy.
	User string `json:"user,omitempty"`
}

// Validate validates this clustersapi auth config bmc
func (m *ClustersapiAuthConfigBmc) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *ClustersapiAuthConfigBmc) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ClustersapiAuthConfigBmc) UnmarshalBinary(b []byte) error {
	var res ClustersapiAuthConfigBmc
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
