// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ClustersapiAdstruct clustersapi adstruct
// swagger:model clustersapiAdstruct
type ClustersapiAdstruct struct {

	// Compartment ID.
	CompartmentID string `json:"compartmentId,omitempty"`

	// Name of the Availability Domain.
	Name string `json:"name,omitempty"`
}

// Validate validates this clustersapi adstruct
func (m *ClustersapiAdstruct) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *ClustersapiAdstruct) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ClustersapiAdstruct) UnmarshalBinary(b []byte) error {
	var res ClustersapiAdstruct
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
