// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ClustersapiGetNodeShapesResponse The response to a get available node shapes request.
// swagger:model clustersapiGetNodeShapesResponse
type ClustersapiGetNodeShapesResponse struct {

	// Array containing the available node shapes.
	BareMetal []string `json:"BareMetal"`
}

// Validate validates this clustersapi get node shapes response
func (m *ClustersapiGetNodeShapesResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateBareMetal(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ClustersapiGetNodeShapesResponse) validateBareMetal(formats strfmt.Registry) error {

	if swag.IsZero(m.BareMetal) { // not required
		return nil
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ClustersapiGetNodeShapesResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ClustersapiGetNodeShapesResponse) UnmarshalBinary(b []byte) error {
	var res ClustersapiGetNodeShapesResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
