// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ClustersapiCreateAuthConfigRequest Schema description.
// swagger:model clustersapiCreateAuthConfigRequest
type ClustersapiCreateAuthConfigRequest struct {

	// bmc
	Bmc *ClustersapiAuthConfigBmc `json:"bmc,omitempty"`

	// The name to assign to the credentials.
	Name string `json:"name,omitempty"`

	// The Wercker organization ID
	OwnerID string `json:"ownerId,omitempty"`
}

// Validate validates this clustersapi create auth config request
func (m *ClustersapiCreateAuthConfigRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateBmc(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ClustersapiCreateAuthConfigRequest) validateBmc(formats strfmt.Registry) error {

	if swag.IsZero(m.Bmc) { // not required
		return nil
	}

	if m.Bmc != nil {

		if err := m.Bmc.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("bmc")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ClustersapiCreateAuthConfigRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ClustersapiCreateAuthConfigRequest) UnmarshalBinary(b []byte) error {
	var res ClustersapiCreateAuthConfigRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
