// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ClustersapiBmcCloudDetails Schema description.
// swagger:model clustersapiBmcCloudDetails
type ClustersapiBmcCloudDetails struct {

	// Parameter description.
	LbShape string `json:"lbShape,omitempty"`

	// Parameter description.
	LbType string `json:"lbType,omitempty"`

	// Parameter description.
	NodeID string `json:"nodeId,omitempty"`
}

// Validate validates this clustersapi bmc cloud details
func (m *ClustersapiBmcCloudDetails) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *ClustersapiBmcCloudDetails) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ClustersapiBmcCloudDetails) UnmarshalBinary(b []byte) error {
	var res ClustersapiBmcCloudDetails
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
