// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ClustersapiGetK8SVersionsResponse The response to a get available Kubernetes version request.
// swagger:model clustersapiGetK8SVersionsResponse
type ClustersapiGetK8SVersionsResponse struct {

	// Kubernetes versions on master nodes.
	Masters []string `json:"masters"`

	// Kubernetes versions on worker nodes.
	Nodes []string `json:"nodes"`
}

// Validate validates this clustersapi get k8 s versions response
func (m *ClustersapiGetK8SVersionsResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateMasters(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateNodes(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ClustersapiGetK8SVersionsResponse) validateMasters(formats strfmt.Registry) error {

	if swag.IsZero(m.Masters) { // not required
		return nil
	}

	return nil
}

func (m *ClustersapiGetK8SVersionsResponse) validateNodes(formats strfmt.Registry) error {

	if swag.IsZero(m.Nodes) { // not required
		return nil
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ClustersapiGetK8SVersionsResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ClustersapiGetK8SVersionsResponse) UnmarshalBinary(b []byte) error {
	var res ClustersapiGetK8SVersionsResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
