// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ClustersapiUpdatePoolsRequest Information required to update the pools of a cluster.
// swagger:model clustersapiUpdatePoolsRequest
type ClustersapiUpdatePoolsRequest struct {

	// Cluster ID.
	ClusterID string `json:"clusterId,omitempty"`

	// Wercker organization ID.
	OwnerID string `json:"ownerId,omitempty"`

	// pools
	Pools ClustersapiUpdatePoolsRequestPools `json:"pools"`
}

// Validate validates this clustersapi update pools request
func (m *ClustersapiUpdatePoolsRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *ClustersapiUpdatePoolsRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ClustersapiUpdatePoolsRequest) UnmarshalBinary(b []byte) error {
	var res ClustersapiUpdatePoolsRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
