// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ClustersapiGetNodeImagesResponse The response to a get available node images request.
// swagger:model clustersapiGetNodeImagesResponse
type ClustersapiGetNodeImagesResponse struct {

	// Array of the available node images.
	Names []string `json:"names"`
}

// Validate validates this clustersapi get node images response
func (m *ClustersapiGetNodeImagesResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateNames(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ClustersapiGetNodeImagesResponse) validateNames(formats strfmt.Registry) error {

	if swag.IsZero(m.Names) { // not required
		return nil
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ClustersapiGetNodeImagesResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ClustersapiGetNodeImagesResponse) UnmarshalBinary(b []byte) error {
	var res ClustersapiGetNodeImagesResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
