// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ClustersapiMetadata Schema description.
// swagger:model clustersapiMetadata
type ClustersapiMetadata struct {

	// Cluster creation date.
	CreatedAt string `json:"createdAt,omitempty"`

	// Cluster creator.
	CreatedBy string `json:"createdBy,omitempty"`

	// Creation work item.
	CreatedByWorkItem string `json:"createdByWorkItem,omitempty"`

	// Cluster deletion date.
	DeletedAt string `json:"deletedAt,omitempty"`

	// Cluster deleter.
	DeletedBy string `json:"deletedBy,omitempty"`

	// Deletion work item.
	DeletedByWorkItem string `json:"deletedByWorkItem,omitempty"`
}

// Validate validates this clustersapi metadata
func (m *ClustersapiMetadata) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *ClustersapiMetadata) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ClustersapiMetadata) UnmarshalBinary(b []byte) error {
	var res ClustersapiMetadata
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
